# Generated by Django 6.0.6 on 2026-07-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('course_name', models.CharField(max_length=200)),
                ('instructor', models.CharField(max_length=100)),
                ('credit', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
