# Generated by Django 6.0.6 on 2026-07-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_learningmaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningmaterial',
            name='file_link',
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='file',
            field=models.FileField(default='', upload_to='course_materials/'),
            preserve_default=False,
        ),
    ]
